name: Docker Image CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: checkout sources
        uses: actions/checkout@v2.3.4
        
      - name: Build an image from Dockerfile
        run: docker build -t 98tam/demo:latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Declare commmit hash variable
        id: vars
        shell: bash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 98tam/demo:latest, tam98/demo:${{ steps.vars.outputs.sha_short }}
